// firestoreSeeder.js
const { db } = require("../connectors/dbconnect");
const moment = require("moment");
const collection = "importacionEnc";

const registrosAInsertar = [
  {
    bl: "A1",
    embarcador: "EMBARCADOR_A1",
    consignatario: "CONSIGNATARIO_A1",
    fechaSalida: moment("2022-01-01"),
    contenedor: "CONTENEDOR_A1",
    barco: "BARCO_A1",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2022-02-25"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A2",
    embarcador: "EMBARCADOR_A2",
    consignatario: "CONSIGNATARIO_A2",
    fechaSalida: moment("2022-02-02"),
    contenedor: "CONTENEDOR_A2",
    barco: "BARCO_A2",
    puertoOrigen: "SHEKOU",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2022-03-14"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A3",
    embarcador: "EMBARCADOR_A3",
    consignatario: "CONSIGNATARIO_A3",
    fechaSalida: moment("2022-03-03"),
    contenedor: "CONTENEDOR_A3",
    barco: "BARCO_A3",
    puertoOrigen: "SHEKOU",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2022-04-15"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A4",
    embarcador: "EMBARCADOR_A4",
    consignatario: "CONSIGNATARIO_A4",
    fechaSalida: moment("2022-04-04"),
    contenedor: "CONTENEDOR_A4",
    barco: "BARCO_A4",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2022-04-29"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A5",
    embarcador: "EMBARCADOR_A5",
    consignatario: "CONSIGNATARIO_A5",
    fechaSalida: moment("2022-05-05"),
    contenedor: "CONTENEDOR_A5",
    barco: "BARCO_A5",
    puertoOrigen: "SHEKOU",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2022-06-13"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A6",
    embarcador: "EMBARCADOR_A6",
    consignatario: "CONSIGNATARIO_A6",
    fechaSalida: moment("2022-06-06"),
    contenedor: "CONTENEDOR_A6",
    barco: "BARCO_A6",
    puertoOrigen: "IZTAPA",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2022-07-16"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A7",
    embarcador: "EMBARCADOR_A7",
    consignatario: "CONSIGNATARIO_A7",
    fechaSalida: moment("2022-07-07"),
    contenedor: "CONTENEDOR_A7",
    barco: "BARCO_A7",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2022-08-23"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A8",
    embarcador: "EMBARCADOR_A8",
    consignatario: "CONSIGNATARIO_A8",
    fechaSalida: moment("2022-08-08"),
    contenedor: "CONTENEDOR_A8",
    barco: "BARCO_A8",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2022-08-14"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A9",
    embarcador: "EMBARCADOR_A9",
    consignatario: "CONSIGNATARIO_A9",
    fechaSalida: moment("2022-09-09"),
    contenedor: "CONTENEDOR_A9",
    barco: "BARCO_A9",
    puertoOrigen: "QUETZAL",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2022-10-24"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A10",
    embarcador: "EMBARCADOR_A10",
    consignatario: "CONSIGNATARIO_A10",
    fechaSalida: moment("2022-10-10"),
    contenedor: "CONTENEDOR_A10",
    barco: "BARCO_A10",
    puertoOrigen: "QUETZAL",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2022-10-25"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A11",
    embarcador: "EMBARCADOR_A11",
    consignatario: "CONSIGNATARIO_A11",
    fechaSalida: moment("2022-11-11"),
    contenedor: "CONTENEDOR_A11",
    barco: "BARCO_A11",
    puertoOrigen: "QUETZAL",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2023-02-09"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A12",
    embarcador: "EMBARCADOR_A12",
    consignatario: "CONSIGNATARIO_A12",
    fechaSalida: moment("2022-12-12"),
    contenedor: "CONTENEDOR_A12",
    barco: "BARCO_A12",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2023-02-19"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A13",
    embarcador: "EMBARCADOR_A13",
    consignatario: "CONSIGNATARIO_A13",
    fechaSalida: moment("2023-01-13"),
    contenedor: "CONTENEDOR_A13",
    barco: "BARCO_A13",
    puertoOrigen: "IZTAPA",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2023-02-06"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A14",
    embarcador: "EMBARCADOR_A14",
    consignatario: "CONSIGNATARIO_A14",
    fechaSalida: moment("2023-02-14"),
    contenedor: "CONTENEDOR_A14",
    barco: "BARCO_A14",
    puertoOrigen: "QUETZAL",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2023-04-10"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A15",
    embarcador: "EMBARCADOR_A15",
    consignatario: "CONSIGNATARIO_A15",
    fechaSalida: moment("2023-03-15"),
    contenedor: "CONTENEDOR_A15",
    barco: "BARCO_A15",
    puertoOrigen: "QUETZAL",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2023-06-11"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A16",
    embarcador: "EMBARCADOR_A16",
    consignatario: "CONSIGNATARIO_A16",
    fechaSalida: moment("2023-04-16"),
    contenedor: "CONTENEDOR_A16",
    barco: "BARCO_A16",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2023-04-27"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A17",
    embarcador: "EMBARCADOR_A17",
    consignatario: "CONSIGNATARIO_A17",
    fechaSalida: moment("2023-05-17"),
    contenedor: "CONTENEDOR_A17",
    barco: "BARCO_A17",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2023-07-13"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A18",
    embarcador: "EMBARCADOR_A18",
    consignatario: "CONSIGNATARIO_A18",
    fechaSalida: moment("2023-06-18"),
    contenedor: "CONTENEDOR_A18",
    barco: "BARCO_A18",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2023-07-04"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A19",
    embarcador: "EMBARCADOR_A19",
    consignatario: "CONSIGNATARIO_A19",
    fechaSalida: moment("2023-07-19"),
    contenedor: "CONTENEDOR_A19",
    barco: "BARCO_A19",
    puertoOrigen: "SHEKOU",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2023-08-05"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A20",
    embarcador: "EMBARCADOR_A20",
    consignatario: "CONSIGNATARIO_A20",
    fechaSalida: moment("2023-08-20"),
    contenedor: "CONTENEDOR_A20",
    barco: "BARCO_A20",
    puertoOrigen: "SHEKOU",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2023-10-22"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A21",
    embarcador: "EMBARCADOR_A21",
    consignatario: "CONSIGNATARIO_A21",
    fechaSalida: moment("2023-09-21"),
    contenedor: "CONTENEDOR_A21",
    barco: "BARCO_A21",
    puertoOrigen: "SHEKOU",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2023-11-14"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A22",
    embarcador: "EMBARCADOR_A22",
    consignatario: "CONSIGNATARIO_A22",
    fechaSalida: moment("2023-10-22"),
    contenedor: "CONTENEDOR_A22",
    barco: "BARCO_A22",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2023-12-01"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A23",
    embarcador: "EMBARCADOR_A23",
    consignatario: "CONSIGNATARIO_A23",
    fechaSalida: moment("2023-11-23"),
    contenedor: "CONTENEDOR_A23",
    barco: "BARCO_A23",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2023-12-09"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A24",
    embarcador: "EMBARCADOR_A24",
    consignatario: "CONSIGNATARIO_A24",
    fechaSalida: moment("2023-12-24"),
    contenedor: "CONTENEDOR_A24",
    barco: "BARCO_A24",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-01-09"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A25",
    embarcador: "EMBARCADOR_A25",
    consignatario: "CONSIGNATARIO_A25",
    fechaSalida: moment("2024-01-01"),
    contenedor: "CONTENEDOR_A25",
    barco: "BARCO_A25",
    puertoOrigen: "QUETZAL",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2024-03-22"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A26",
    embarcador: "EMBARCADOR_A26",
    consignatario: "CONSIGNATARIO_A26",
    fechaSalida: moment("2024-02-02"),
    contenedor: "CONTENEDOR_A26",
    barco: "BARCO_A26",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-03-21"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A27",
    embarcador: "EMBARCADOR_A27",
    consignatario: "CONSIGNATARIO_A27",
    fechaSalida: moment("2024-03-03"),
    contenedor: "CONTENEDOR_A27",
    barco: "BARCO_A27",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-04-07"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A28",
    embarcador: "EMBARCADOR_A28",
    consignatario: "CONSIGNATARIO_A28",
    fechaSalida: moment("2024-04-04"),
    contenedor: "CONTENEDOR_A28",
    barco: "BARCO_A28",
    puertoOrigen: "SHEKOU",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2024-04-13"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A29",
    embarcador: "EMBARCADOR_A29",
    consignatario: "CONSIGNATARIO_A29",
    fechaSalida: moment("2024-05-05"),
    contenedor: "CONTENEDOR_A29",
    barco: "BARCO_A29",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2024-05-27"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A30",
    embarcador: "EMBARCADOR_A30",
    consignatario: "CONSIGNATARIO_A30",
    fechaSalida: moment("2024-06-06"),
    contenedor: "CONTENEDOR_A30",
    barco: "BARCO_A30",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-07-18"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A31",
    embarcador: "EMBARCADOR_A31",
    consignatario: "CONSIGNATARIO_A31",
    fechaSalida: moment("2024-07-07"),
    contenedor: "CONTENEDOR_A31",
    barco: "BARCO_A31",
    puertoOrigen: "SHEKOU",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2024-07-18"),
    estado: "A",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
  },
  {
    bl: "A32",
    embarcador: "EMBARCADOR_A32",
    consignatario: "CONSIGNATARIO_A32",
    fechaSalida: moment("2024-08-08"),
    contenedor: "CONTENEDOR_A32",
    barco: "BARCO_A32",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-10-02"),
    estado: "A",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
  },
  {
    bl: "A33",
    embarcador: "EMBARCADOR_A33",
    consignatario: "CONSIGNATARIO_A33",
    fechaSalida: moment("2024-01-09"),
    contenedor: "CONTENEDOR_A33",
    barco: "BARCO_A33",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-03-12"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A34",
    embarcador: "EMBARCADOR_A34",
    consignatario: "CONSIGNATARIO_A34",
    fechaSalida: moment("2024-02-10"),
    contenedor: "CONTENEDOR_A34",
    barco: "BARCO_A34",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-02-28"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A35",
    embarcador: "EMBARCADOR_A35",
    consignatario: "CONSIGNATARIO_A35",
    fechaSalida: moment("2024-03-11"),
    contenedor: "CONTENEDOR_A35",
    barco: "BARCO_A35",
    puertoOrigen: "SHEKOU",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-04-08"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A36",
    embarcador: "EMBARCADOR_A36",
    consignatario: "CONSIGNATARIO_A36",
    fechaSalida: moment("2024-04-12"),
    contenedor: "CONTENEDOR_A36",
    barco: "BARCO_A36",
    puertoOrigen: "QUETZAL",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2024-04-28"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A37",
    embarcador: "EMBARCADOR_A37",
    consignatario: "CONSIGNATARIO_A37",
    fechaSalida: moment("2024-01-13"),
    contenedor: "CONTENEDOR_A37",
    barco: "BARCO_A37",
    puertoOrigen: "IZTAPA",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-03-20"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A38",
    embarcador: "EMBARCADOR_A38",
    consignatario: "CONSIGNATARIO_A38",
    fechaSalida: moment("2024-02-14"),
    contenedor: "CONTENEDOR_A38",
    barco: "BARCO_A38",
    puertoOrigen: "SHEKOU",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-02-27"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A39",
    embarcador: "EMBARCADOR_A39",
    consignatario: "CONSIGNATARIO_A39",
    fechaSalida: moment("2024-03-15"),
    contenedor: "CONTENEDOR_A39",
    barco: "BARCO_A39",
    puertoOrigen: "QUETZAL",
    puertoDestino: "IZTAPA",
    fechaArribo: moment("2024-05-07"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A40",
    embarcador: "EMBARCADOR_A40",
    consignatario: "CONSIGNATARIO_A40",
    fechaSalida: moment("2024-04-16"),
    contenedor: "CONTENEDOR_A40",
    barco: "BARCO_A40",
    puertoOrigen: "IZTAPA",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-05-20"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A41",
    embarcador: "EMBARCADOR_A41",
    consignatario: "CONSIGNATARIO_A41",
    fechaSalida: moment("2024-05-17"),
    contenedor: "CONTENEDOR_A41",
    barco: "BARCO_A41",
    puertoOrigen: "QUETZAL",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-05-26"),
    estado: "F",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
    usuarioFinaliza: "ADMIN",
    fechaFinaliza: moment(),
  },
  {
    bl: "A42",
    embarcador: "EMBARCADOR_A42",
    consignatario: "CONSIGNATARIO_A42",
    fechaSalida: moment("2024-06-18"),
    contenedor: "CONTENEDOR_A42",
    barco: "BARCO_A42",
    puertoOrigen: "SHEKOU",
    puertoDestino: "SAN JOSE",
    fechaArribo: moment("2024-06-22"),
    estado: "A",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
  },
  {
    bl: "A43",
    embarcador: "EMBARCADOR_A43",
    consignatario: "CONSIGNATARIO_A43",
    fechaSalida: moment("2024-07-19"),
    contenedor: "CONTENEDOR_A43",
    barco: "BARCO_A43",
    puertoOrigen: "SAN JOSE",
    puertoDestino: "SHEKOU",
    fechaArribo: moment("2024-08-24"),
    estado: "A",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
  },
  {
    bl: "A44",
    embarcador: "EMBARCADOR_A44",
    consignatario: "CONSIGNATARIO_A44",
    fechaSalida: moment("2024-08-20"),
    contenedor: "CONTENEDOR_A44",
    barco: "BARCO_A44",
    puertoOrigen: "SHEKOU",
    puertoDestino: "QUETZAL",
    fechaArribo: moment("2024-10-09"),
    estado: "A",
    usuarioCrea: "ADMIN",
    fechaCreacion: moment(),
  },
];

async function seedRegistro() {
  const batch = db.batch();
  const documentoRef = db.collection(collection);

  for (const dato of registrosAInsertar) {
    // Generar un nuevo documento con ID automático
    const nuevoDoc = documentoRef.doc();
    batch.set(nuevoDoc, dato);
  }

  try {
    await batch.commit();
    console.log(`${registrosAInsertar.length} datos insertados correctamente`);
  } catch (error) {
    console.error("Error al insertar dato:", error);
  }
}

seedRegistro();
